# Generated by Django 5.2.9 on 2025-12-17 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-адрес')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='Логотип')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (RU)')),
                ('description_uz', models.TextField(blank=True, verbose_name='Описание (UZ)')),
                ('description_en', models.TextField(blank=True, verbose_name='Описание (EN)')),
                ('website', models.URLField(blank=True, verbose_name='Веб-сайт')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Верифицирован')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемый')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'db_table': 'brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL-адрес')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название (RU)')),
                ('name_uz', models.CharField(blank=True, max_length=200, verbose_name='Название (UZ)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Название (EN)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (RU)')),
                ('description_uz', models.TextField(blank=True, verbose_name='Описание (UZ)')),
                ('description_en', models.TextField(blank=True, verbose_name='Описание (EN)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Изображение')),
                ('icon', models.CharField(blank=True, help_text='Название иконки Lucide (например: tractor, wrench)', max_length=50, verbose_name='Иконка')),
                ('meta_title_ru', models.CharField(blank=True, max_length=70, verbose_name='Meta Title (RU)')),
                ('meta_description_ru', models.CharField(blank=True, max_length=160, verbose_name='Meta Description (RU)')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'categories',
                'ordering': ['order', 'name_ru'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('sku', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Артикул')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL-адрес')),
                ('product_type', models.CharField(choices=[('machinery', 'Сельхозтехника'), ('attachment', 'Навесное оборудование'), ('spare_part', 'Запчасть')], default='machinery', max_length=20, verbose_name='Тип товара')),
                ('name_ru', models.CharField(max_length=300, verbose_name='Название (RU)')),
                ('name_uz', models.CharField(blank=True, max_length=300, verbose_name='Название (UZ)')),
                ('name_en', models.CharField(blank=True, max_length=300, verbose_name='Название (EN)')),
                ('short_description_ru', models.TextField(blank=True, verbose_name='Краткое описание (RU)')),
                ('short_description_uz', models.TextField(blank=True, verbose_name='Краткое описание (UZ)')),
                ('short_description_en', models.TextField(blank=True, verbose_name='Краткое описание (EN)')),
                ('full_description_ru', models.TextField(blank=True, verbose_name='Полное описание (RU)')),
                ('full_description_uz', models.TextField(blank=True, verbose_name='Полное описание (UZ)')),
                ('full_description_en', models.TextField(blank=True, verbose_name='Полное описание (EN)')),
                ('base_price_usd', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Базовая цена (USD)')),
                ('retail_price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Розничная цена (USD)')),
                ('wholesale_price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Оптовая цена (USD)')),
                ('show_price_to_guests', models.BooleanField(default=False, verbose_name='Показывать цену гостям')),
                ('stock_status', models.CharField(choices=[('in_stock', 'В наличии'), ('low_stock', 'Мало'), ('pre_order', 'Под заказ'), ('out_of_stock', 'Нет в наличии')], default='in_stock', max_length=20, verbose_name='Статус наличия')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Количество на складе')),
                ('warehouse_location', models.CharField(blank=True, max_length=100, verbose_name='Склад')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Вес (кг)')),
                ('length_cm', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длина (см)')),
                ('width_cm', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ширина (см)')),
                ('height_cm', models.PositiveIntegerField(blank=True, null=True, verbose_name='Высота (см)')),
                ('ships_from', models.CharField(default='Ташкент', max_length=100, verbose_name='Отправка из')),
                ('estimated_delivery_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Срок доставки (дней)')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Главное изображение')),
                ('video_url', models.URLField(blank=True, verbose_name='Видео (URL)')),
                ('specifications', models.JSONField(blank=True, default=dict, help_text='\n        Пример: {\n            "horsepower": {"value": 120, "unit": "л.с."},\n            "engine_type": {"value": "Дизель YTO 4-цилиндра"},\n            "fuel_capacity": {"value": 200, "unit": "л"}\n        }\n        ', verbose_name='Технические характеристики')),
                ('meta_title_ru', models.CharField(blank=True, max_length=70, verbose_name='Meta Title (RU)')),
                ('meta_description_ru', models.CharField(blank=True, max_length=160, verbose_name='Meta Description (RU)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемый')),
                ('is_configurable', models.BooleanField(default=False, verbose_name='Конфигурируемый')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.brand', verbose_name='Бренд')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('doc_type', models.CharField(choices=[('brochure', 'Брошюра'), ('manual', 'Руководство'), ('certificate', 'Сертификат'), ('spec_sheet', 'Спецификация')], max_length=20, verbose_name='Тип документа')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Файл')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('uz', "O'zbek"), ('en', 'English')], default='ru', max_length=5, verbose_name='Язык')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Документ товара',
                'verbose_name_plural': 'Документы товаров',
                'db_table': 'product_documents',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Изображение')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Alt-текст')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_schematic', models.BooleanField(default=False, help_text='Для разнесённых схем запчастей', verbose_name='Схема/чертёж')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
                'db_table': 'product_images',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='products_sku_fe2039_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='products_categor_9e60b3_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'is_active'], name='products_brand_i_2684af_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type', 'is_active'], name='products_product_6ea65b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['stock_status'], name='products_stock_s_89e512_idx'),
        ),
    ]
