# Generated by Django 5.2.9 on 2025-12-17 04:19

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='Код региона')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название (RU)')),
                ('name_uz', models.CharField(max_length=100, verbose_name='Название (UZ)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Название (EN)')),
                ('delivery_days_min', models.PositiveIntegerField(default=1, verbose_name='Мин. дней доставки')),
                ('delivery_days_max', models.PositiveIntegerField(default=5, verbose_name='Макс. дней доставки')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'db_table': 'regions',
                'ordering': ['name_ru'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('guest', 'Гость'), ('farmer', 'Фермер (физ. лицо)'), ('business', 'Бизнес (юр. лицо)'), ('dealer', 'Региональный дилер'), ('admin', 'Администратор')], default='guest', max_length=20, verbose_name='Тип пользователя')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, verbose_name='Телефон')),
                ('telegram_id', models.BigIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='Telegram ID')),
                ('telegram_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram username')),
                ('preferred_language', models.CharField(choices=[('ru', 'Русский'), ('uz', "O'zbek"), ('en', 'English')], default='ru', max_length=5, verbose_name='Предпочитаемый язык')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Район')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('inn', models.CharField(db_index=True, max_length=9, unique=True, verbose_name='ИНН')),
                ('company_name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('legal_address', models.TextField(verbose_name='Юридический адрес')),
                ('vat_payer', models.BooleanField(default=False, verbose_name='Плательщик НДС')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата верификации')),
                ('verification_data', models.JSONField(blank=True, default=dict, help_text='Raw response from Soliq.uz API', verbose_name='Данные верификации')),
                ('pricing_tier', models.CharField(choices=[('retail', 'Розница'), ('wholesale', 'Опт'), ('vip', 'VIP')], default='retail', max_length=20, verbose_name='Ценовая категория')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Кредитный лимит (USD)')),
                ('contact_name', models.CharField(blank=True, max_length=200, verbose_name='Контактное лицо')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Контактный телефон')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Бизнес-профиль',
                'verbose_name_plural': 'Бизнес-профили',
                'db_table': 'business_profiles',
            },
        ),
    ]
